---
all:
  vars:
    ansible_user: ducnam
  children:
    k8s:
      children:
        masters:
          hosts:
            k8s-master:
              ansible_host: 10.1.68.140
        workers:
          hosts:
            k8s-worker:
              ansible_host: 10.1.68.141
...
