---
version: 3

images:
  base_image:
    name: registry.access.redhat.com/ubi9/ubi:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
  # Giải pháp chính thống của Red Hat để bỏ qua các gói hệ thống bị lỗi của Collection
  exclude:
    system:
      - openshift-clients
options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: ansible.cfg
    dest: conf.d/
  - src: private_automation_hub-ca.pem
    dest: certs/

additional_build_steps:
  prepend_galaxy:
    - COPY _build/conf.d/ansible.cfg /home/runner/.ansible.cfg
    - COPY _build/certs/private_automation_hub-ca.pem /etc/pki/ca-trust/source/anchors
    - RUN update-ca-trust
