---
- name: Tu dong don dep cac Pod job da chay thanh cong
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: 1. Lay danh sach cac Pod da hoan thanh (Succeeded)
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: awx
        field_selectors:
          - status.phase=Succeeded
      register: succeeded_pods

    - name: 2. Xoa tung Pod hoan thanh khoi he thong
      kubernetes.core.k8s:
        state: absent
        kind: Pod
        namespace: awx
        name: "{{ item.metadata.name }}"
      loop: "{{ succeeded_pods.resources }}"
      when: succeeded_pods.resources | length > 0
...
