---
- name: Tu dong don dep cac Pod job da chay thanh cong
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: Don dep cac Pod trang thai Succeeded bang module K8s
      kubernetes.core.k8s:
        state: absent
        kind: Pod
        namespace: awx
        field_selectors:
          - status.phase=Succeeded
...
